Add external links popup to OSM / Google Maps
TUM-Dev/navigatum pull request #136
Opened 2022-06-07 21:35 UTC by octycs

This adds a small popup with links to OSM and Google Maps. The Google Maps links _should_ directly open the app on Android and according to the internet also on iOS.

Currently the popup is implemented CSS only. This appeared to work, we have to see whether this causes issues.

![image](https://user-images.githubusercontent.com/7429408/172486132-7b0926a4-f72b-4850-970f-82ca6babbb65.png)

Solves #87

2022-06-07 22:27 UTC, CommanderStorm requested changes
- Would it be possible to add a "Copy Link" button, that literally copies the current website link to the clipboard like the one we already have?

- On mobile may want to support https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share
On some platforms (Namely anything linux) this is however "creatively" implemented.
On Mobile this looks like this:
![Screenshot_20220608-001710_Chrome](https://user-images.githubusercontent.com/26258709/172492691-675fdbb3-52bb-4bd9-8644-eb93247f5647.jpg)
As a link we might share sometthing like `geo:latitude,longitude` as suggested [here](https://stackoverflow.com/questions/15053004/how-to-generate-a-location-link-that-will-open-in-default-mapping-app) and/or the sites link.

Request changes is because I currently consider the share icon a bit misleading without any sharing functionality... 
This is still an improvement and could be merged, but I would prefer an a bit different messaging.
The second point can go into an issue and live there, as essentially I am not shure how this really should be implemented, but maybe you have a good idea for this dilemma

2022-06-07 22:27 UTC, CommanderStorm commented on webclient/src/views/view/view-view.inc
> +             :href="'https://www.google.com/maps/search/?api=1&query=' + view_data.coords.lat + '%2C'+ view_data.coords.lon">Google Maps</a>
I would prefer a "Open in XY" (obviously localised)
Reasoning:
We are using a share button and we are not shareing to OSM/Maps, but opening the location in this app.

2022-06-07 22:32 UTC, CommanderStorm commented
An example for a less supported platform for the API I referenced can be seen here:
![image](https://user-images.githubusercontent.com/26258709/172494096-b016d456-b156-436d-bdf0-604a262910b4.png)
(Manjaro, Linux, Chrome)

2022-06-12 20:19 UTC, octycs commented
Now this also supports Sharing:
![image](https://user-images.githubusercontent.com/7429408/173252058-78f7a93b-5fa4-4c6e-86ac-8a0d7e4979bf.png)

The Geo URI is behind the 'other app' button, and the browser share functionality is only visible if the browser supports sharing (which neither Chrome nor Firefox do on my system for some reason).

2022-06-12 21:57 UTC, CommanderStorm approved these changes

2022-06-12 21:59 UTC, merged