Show the campus in the search subtext and add short names for buildings etc.
TUM-Dev/navigatum pull request #196
Opened 2022-08-18 12:07 UTC by octycs

This PR adds the campus to the search result subtext. Because this would produce too long subtexts sometimes, it also introduces short names for them.

The main motivation is that probably not many know the names of buildings like "Bestelmeyer", so it's probably helpful to show the campus as well.

Screenshot:
![image](https://user-images.githubusercontent.com/7429408/185390441-1e79a4a3-0151-4f5b-b294-22586bf08269.png)

2022-08-19 19:03 UTC, CommanderStorm requested changes
Overall I think this is a good adition, but I think, that a few more buildings (Raitenhaslach, Berchtesgarden, ...) from the areatree could use the shortnames.
The other comments are minor

2022-08-19 19:03 UTC, CommanderStorm commented on data/sources/00_areatree
> +      0201:StudiTUM Innenstadt (S1)|StudiTUM:0201,studitum-innenstadt
As a clarification on how the last part is hadled (I dont want to look through the parser):
what does `studitum-innenstadt` in this case mean? https://nav.tum.sexy/building/studitum-innenstadt is not availiable..

2022-08-19 19:03 UTC, CommanderStorm commented on server/src/core/search/search_executor/postprocess.rs
> +) -> String {
I have not tested, if rustfmt likes this, but I assume it does
```suggestion
fn generate_subtext(hit: &meilisearch::MSHit) -> String {
```

2022-08-21 12:58 UTC, octycs commented on data/processors/areatree.py
> +    building_data["name"] = names[0]
I've added a warning if it is longer than 20 chars

2022-08-21 13:00 UTC, octycs commented on data/sources/00_areatree
> +      0201:StudiTUM Innenstadt (S1)|StudiTUM:0201,studitum-innenstadt
It's not implemented but the idea was that there can be additional, more human readable ids that are only used for the URLs

2022-08-21 13:43 UTC, CommanderStorm commented on data/sources/00_areatree
> +      0201:StudiTUM Innenstadt (S1)|StudiTUM:0201,studitum-innenstadt
Could you write an issue for this? 😉
I can do it if you'd like..

2022-08-21 13:45 UTC, CommanderStorm approved these changes

2022-08-22 18:55 UTC, octycs commented on data/sources/00_areatree
> +      0201:StudiTUM Innenstadt (S1)|StudiTUM:0201,studitum-innenstadt
Created it: #199

2022-08-22 18:56 UTC, merged