Removed the sourcecode handler
TUM-Dev/NavigaTUM pull request #367
Opened 2023-01-27 22:15 UTC by CommanderStorm

## Proposed Changes (include Screenshots if possible)

- This PR removes the source code handlers
- Reasoning:
  - For debugging, I don't consider this useful
  - Why keep something that is not useful?

## How to test this PR

1. Discuss if sourcecode is not needed instead

## How has this been tested?

- internal monolouge, that this feature is not needed

## Checklist:

- [x] I have updated the documentation / No need to update the documentation
- [x] I have run the linter

2023-01-27 23:35 UTC, octycs commented
Since it's GPL (as said in the doc), we don't need to have it. For me it's kind of equal whether to keep it or to remove it. It follows the idea of GPL to provide access to the source code (so it wasn't intended for debugging anyway), but the repo is also directly accessible from the NavigaTUM website. The only thing is that people without access to the deployment might not know which commit is currently active. But if you say it's rather unnecessary or even standing in the way, I am okay to remove it.

2023-01-28 00:11 UTC, CommanderStorm commented
> The only thing is that people without access to the deployment might not know which commit is currently active.

Normally I would respond that this never happens and if it does it would be my job to spot this via the alerting we have.
But #352 has shown me some gaps in my alerting for which I really dont have a good way to adress them, so you are probably right.
Thinking more about this, I think this should be combining the `health` and the `source_code` endpoint into a `status` endpoint.

2023-01-29 22:20 UTC, octycs requested changes

2023-01-29 22:20 UTC, octycs commented on server/src/main.rs
>  async fn health_handler() -> HttpResponse {
Shouldn't this also be adapted?

2023-01-29 22:21 UTC, octycs commented
> Thinking more about this, I think this should be combining the health and the source_code endpoint into a status endpoint.
That's a good compromise :+1:

2023-01-30 00:27 UTC, CommanderStorm commented on server/src/main.rs
>  async fn health_handler() -> HttpResponse {
Ups

2023-01-31 21:11 UTC, octycs approved these changes

2023-02-01 17:04 UTC, merged