check if coordinates are within a certain window
TUM-Dev/NavigaTUM pull request #716
Opened 2023-07-09 15:59 UTC by quarz12

implements [131](https://github.com/TUM-Dev/NavigaTUM/issues/131)

## Proposed Changes (include Screenshots if possible)

- checks if coordinates are within this window. If not, throw exception (maybe deleting the coords attibute works too? I noticed the interactive map shows munich if theres no coords field provided)
![image](https://github.com/TUM-Dev/NavigaTUM/assets/64491670/d3ad443a-8020-4f82-98d6-4bba37db0965)

## How to test this PR

- run compile.py

## How has this been tested?

^

## Checklist

- [x] I have updated the documentation / No need to update the documentation
- [ ] I have run the linter

2023-07-09 16:29 UTC, CommanderStorm requested changes
- I think there are different approaches which could catch more errors than just overlaying a rectangle globally.
This check will, for example, not find if there is one room far, far outside the bounds of a building.
  A distance-based approach with either hardcoded or inferred distance from the room-corpus is a better approach:
  ```py
  if (distance_to_parent(data) > infered_maximum_distance_between_room_and_parent[...]):
  ```
  I would prefer an approach which infers the distance based on a percentile of the data * constant factor
- with the current approach, this won't build for 
  -> I would prefer these issues to be addressed in this PR.
  This can be done by
  - deleting the coordinates (override with no coordinate),
  - overriding with the parent,
  - overriding with a manually inferred/accurate coordinate or
  - making this a warning instead of a `Exception`

2023-07-09 16:38 UTC, CommanderStorm commented
(sorry, I accidentally rebased your branch too instead of merging into it)

2023-07-09 17:29 UTC, quarz12 commented
I agree that this approach is quite inaccurate. I was not sure if I could assume building locations to be correct. That opens up way better solutions.

2023-07-09 18:20 UTC, quarz12 commented
>I would prefer an approach which infers the distance based on a percentile of the data * constant factor

I am not sure I understand this right. Does this mean values should be accepted, if a certain percentile of rooms is close enough nearby?

2023-07-09 19:14 UTC, CommanderStorm commented
> I was not sure if I could assume building locations to be correct

All building locations can be assumed to be correct and are to some part manually sourced.
If there is a significant variation between the rooms and the building, that would still be interesting though ^^

2023-07-09 20:07 UTC, quarz12 commented
> If there is a significant variation between the rooms and the building, that would still be interesting though ^^
well, there are a lot of rooms in 0510 that are about 2km away from their building. looking at the 0510 coords, I'd assume that that one is incorrect though. What do you think is a good maximum distance? I did some test runs, and it looks like all correct values are easily within 100m, so I'd suggest that.

2023-07-09 21:27 UTC, quarz12 commented
I think this is now at a point where I can say that I am happy with the solution.
I know you gave me merge permissions on this repo, but I think I am still too new to this project to make this decision alone.

2023-07-10 02:11 UTC, CommanderStorm requested changes
I have made some style-inline comments.
There are still quite a lot of linting issues in this PR. Please run the linter (included in `pre-commit`, see the Readme for further details) next time before requesting a review ^^

2023-07-10 02:11 UTC, CommanderStorm commented
> I know you gave me merge permissions on this repo, but I think I am still too new to this project to make this decision alone.  

Honestly, this was not intentional. I have changed a setting and this should not be possible anymore.
I was trying to give you the permission to run github-actions (like the CI) by yourself.
While for this PR this will not make a difference (https://github.com/TUM-Dev/NavigaTUM/pull/712 is not yet mergable), I thought the feedback if the docker files build could be valable feedback.

2023-07-10 09:09 UTC, quarz12 commented
>Please run the linter (included in pre-commit

I thought, if I have installed that, it would automatically run? Is there a way to only run it for a single file? --all-files bloats my changes log with other files that then prevent me from switching branches until I delete them again.
>>I know you gave me merge permissions on this repo, but I think I am still too new to this project to make this decision alone.

>Honestly, this was not intentional. I have changed a setting and this should not be possible anymore.

I did think that was a bit much😅

2023-07-10 09:41 UTC, quarz12 commented on data/processors/coords.py
> +
for some buildings, when room and building coords are the same, ```sin(lat1) * sin(lat2) + cos(lat1) * cos(lat2) * cos(lon1 - lon2)``` returns a value like 1.0000000000000002. 
Which means acos raises an exception as it is bigger than 1.
I guess a better solution would be to use Decimals in the distance func.

2023-07-11 23:20 UTC, CommanderStorm commented on data/processors/coords.py
> +MAX_DISTANCE_METERS_FROM_PARENT = 100
Pushing this to `200` resolves two false positives

```suggestion
MAX_DISTANCE_METERS_FROM_PARENT = 200
```

2023-07-11 23:26 UTC, CommanderStorm approved these changes

2023-07-11 23:26 UTC, CommanderStorm commented on data/processors/coords.py
> +        if not data["type"] == "room":
```suggestion
        if data["type"] != "room":
```

2023-07-11 23:26 UTC, CommanderStorm commented on data/processors/coords.py
> +            )
```suggestion
            logging.warning(
                f"{iid} {coords} is {distance_to_parent}m away from its parent {parent_id} {parent_coords}. "
                "Please recheck if the coordinate makes sense",
            )
```

2023-07-11 23:30 UTC, CommanderStorm commented on data/processors/coords.py
> +def validate_coords(input_data):
Added a method docstring
```suggestion
def validate_coords(input_data):
    """Check that coordinates are not too far away from their parent"""
```

2023-07-11 23:30 UTC, CommanderStorm commented on data/processors/coords.py
> +
I like the current solution much better 👍🏻

2023-07-11 23:44 UTC, merged

2023-07-11 23:44 UTC, CommanderStorm commented
Thank you for implementing this ❤️